### ISSUE TITLE
Datasource pool advanced configuration options 

### ISSUE THREAD

**Issue by TFaga** [kumuluz/kumuluzee#41]
KumuluzEE is using the HikariCP for its implementation of the Datasource configuration pool, but it is currently lacking any advanced configuration options that HikariCP provides (except for the max pool size).

I propose all the available HikariCP configuration options are added to the KumuluzEE configuration options.

**Comment by salvadormarcos** [comment]
What do you think of using a JCA (JavaEE Connector Architecture) implementation instead HikariCP? With this feature, the project would be closer to a JavaEE Application Server.

I have been doing some testing with JBoss IronJacamar and I have gotten advanced options like "min pool size", "initial pool size", "connection validation", etc for Jdbc Local/XA connections. Even JTA transactions work with Local JDBC connections.

I can submit my code as Pull Request, but the code structure is still in 2.3.0.beta1 version.

**Comment by MBJuric** [comment]
Hi Marcos,
This is definitely interesting. If I understand correctly, JBoss IronJacamar provides full JCA 1.7 support. Adding this to KumuluzEE is definitely interesting. 
Please submit the code, however we might need some more time to have a look, as we are currently very busy implementing new features (you might have noticed the KumuluzEE extensions and improvements in version 2.3 that we have just released). 
On the other hand, if there would be a chance for you to update the code for 2.3 (or the upcoming 2.4) and maybe include KumuluzEE Config support for configuring various parameters, that would be extremely welcome and much appreciated. 
Thanks, Matjaz

**Comment by salvadormarcos** [comment]
You're right, JBoss IronJacamar provides full JCA 1.7 support in JBoss AS/WildFly. It can still be embedded in other web servers like Jetty/Tomcat.

I will adapt my code to version 2.4 and in a few days I submit the Pull Request.

However, I have no knowledge about Consult/Etcd to implement the Kumuluz Config support. Sorry for my lack of knowledge, I would need more time to study these technologies.

Thanks for the receptivity!

**Comment by MBJuric** [comment]
That's great. Much appreciated and thanks in advance. 
Regarding configuration, I didn’t mean to use etcd or Consul, but the build-in config framework for configuration from ENV variables, config files or properties: https://github.com/kumuluz/kumuluzee/wiki/Configuration
The idea is that instead of using original configuration (which can be difficult to manage in microservice environment), you can configure everything through KumuluzEE Config. BTW, once this is supported it also automatically works with config server, such as etcd or Consul.
Example, how we have done it with TLS/SSL: https://github.com/kumuluz/kumuluzee/blob/master/core/src/main/java/com/kumuluz/ee/factories/EeConfigFactory.java
If you have any questions, please do not hesitate to contact us. 
Thanks, Matjaz
